#!/bin/sh

cd $(dirname $0)/..


target="$(pwd)/bin/strappy"
destination="/usr/local/bin/strappy"

read -d '' cmd <<-EOF
#!/bin/sh

$target "\$@"
EOF

rm -f $destination
echo "$cmd" > $destination
chmod +x $destination
