#!/usr/bin/env bash

cd "$(dirname "$0")"/.. || exit

target="$(pwd)/bin/strappy"
destination="/usr/local/bin/strappy"

read -rd '' cmd <<-EOF
#!/usr/bin/env bash

$target "\$@"
EOF

rm -f $destination
echo "$cmd" > $destination
chmod +x $destination
